name: CalculationCommands
main: SalmonDE\CalculationCommands\Loader
author: SalmonDE
version: 1.0.0
api: [3.5.0, 4.0.0]
permissions:
    cmd:
        children:
            cmd.calculate:
                children:
                    cmd.calculate.add:
                        default: true
                    cmd.calculate.divide:
                        default: true
                    cmd.calculate.multiply:
                        default: true
                    cmd.calculate.subtract:
                        default: true
